[[ISSUERS]]
address = "rGX1muKbU2j1vob1B5e8idbNH2pF93hy3k"
name = "SOLX SOLANA ON XRP"

[[TOKENS]]
issuer = "rGX1muKbU2j1vob1B5e8idbNH2pF93hy3k"
currency = "SOLX"
name = "SOLX SOLANA ON XRP"
desc = "Happy New Year 2025!"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
